# QUERY 1 – Alle Universitäten
# Einfachste mögliche Abfrage: 1 Typ-Bedingung, 1 Label
# Zeigt: PREFIX, SELECT, WHERE, Variable (?u / ?name)

PREFIX uni:  <http://example.org/uni/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?u ?name
WHERE {
    ?u a uni:University .
    ?u rdfs:label ?name .
}
ORDER BY ?name
